
[font]
size = 12.0

[font.bold]
family = "iosevka"
style = "Bold"

[font.bold_italic]
family = "iosevka"
style = "Bold Italic"

[font.italic]
family = "iosevka"
style = "Italic"

[font.normal]
family = "iosevka"
style = "Regular"

[keyboard]
bindings = [
    { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
    { key = "N", mods = "Control", action = "SpawnNewInstance" },
    { key = "Backspace", mods = "Control", chars = "\U00000001B\U00000062" },
]

# enable clicking on line numbers to open crate in vscode
[[hints.enabled]]
regex = "[^ ]+\\.rs:\\d+:\\d+"
command = { program = "code", args = ["--goto"] }
mouse = { enabled = true }

# window settings
[window]
padding = { x = 30, y = 30 }
decorations = "Full"
dimensions = { columns = 80, lines = 17 }

[cursor]
style = { shape = "Beam", blinking = "On" }

[terminal]
osc52 = "CopyPaste"

[general]
# import theme
import = ["~/.config/alacritty/current_theme.toml"]
